### PR TITLE
Development

### PR DESCRIPTION
**Pull request by keshav-c**
Awaiting review

### CODE REVIEW

**Comment by azdrenymeri** [comment]
## Hello @keshav-c  :wave: 
### Good Job
* `my_count` should cover three input cases
   * when no argument and nor blocks is given it should return the count of the entire array
   * When an argument is given it should return the count of items equals to that argument
   * When a block is given
#### Your method covers only the last one
##### simple hint 
```Ruby
ary = [1, 2, 4, 2]
ary.my_count                  #=> 4 (the array contains 4 elements)
ary.my_count(2)               #=> 2 (there are two elements equals to argument 2)
ary.my_count { |x| x%2 == 0 } #=> 3 (there are 3 even numbers in the array)
```
###  Fix this and add it for a re-review

**Comment by keshav-c** [comment]
Done. New method signature `my_count(element=nil)`

**Comment by azdrenymeri** [comment]
### Nice job @keshav-c  :1st_place_medal: 
#### It's a thumbs up from me :+1: 
#### You can go ahead and merge no further requests from my side

**Comment by keshav-c** [comment]
Thanks

**Pull request merged**
